// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanetHunters.Data;

namespace PlanetHunters.Data.Migrations
{
    [DbContext(typeof(PlanetHuntersDbContext))]
    partial class PlanetHuntersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PlanetHunters.Models.Astronomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Astronomers");
                });

            modelBuilder.Entity("PlanetHunters.Models.AstronomerDiscovery", b =>
                {
                    b.Property<int>("AstronomerId");

                    b.Property<int>("DiscoveryId");

                    b.HasKey("AstronomerId", "DiscoveryId");

                    b.HasIndex("DiscoveryId");

                    b.ToTable("AstronomersDiscoveries");
                });

            modelBuilder.Entity("PlanetHunters.Models.Discovery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateMade");

                    b.Property<int>("TelescopeId");

                    b.HasKey("Id");

                    b.HasIndex("TelescopeId");

                    b.ToTable("Discoveries");
                });

            modelBuilder.Entity("PlanetHunters.Models.ObserverDiscovery", b =>
                {
                    b.Property<int>("ObserverId");

                    b.Property<int>("DiscoveryId");

                    b.HasKey("ObserverId", "DiscoveryId");

                    b.HasIndex("DiscoveryId");

                    b.ToTable("ObserversDiscoveries");
                });

            modelBuilder.Entity("PlanetHunters.Models.Planet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DiscoveryId");

                    b.Property<int>("HostStarSystemId");

                    b.Property<double>("Mass");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("DiscoveryId");

                    b.HasIndex("HostStarSystemId");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("PlanetHunters.Models.Star", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DiscoveryId");

                    b.Property<int>("HostStarSystemId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("Temperature");

                    b.HasKey("Id");

                    b.HasIndex("DiscoveryId");

                    b.HasIndex("HostStarSystemId");

                    b.ToTable("Stars");
                });

            modelBuilder.Entity("PlanetHunters.Models.StarSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("StarSystems");
                });

            modelBuilder.Entity("PlanetHunters.Models.Telescope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location");

                    b.Property<double?>("MirrorDiameter");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Telescopes");
                });

            modelBuilder.Entity("PlanetHunters.Models.AstronomerDiscovery", b =>
                {
                    b.HasOne("PlanetHunters.Models.Astronomer", "Astronomer")
                        .WithMany("PioneeringDiscoveries")
                        .HasForeignKey("AstronomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PlanetHunters.Models.Discovery", "Discovery")
                        .WithMany("Astronomers")
                        .HasForeignKey("DiscoveryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PlanetHunters.Models.Discovery", b =>
                {
                    b.HasOne("PlanetHunters.Models.Telescope", "Telescope")
                        .WithMany("Discoveries")
                        .HasForeignKey("TelescopeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PlanetHunters.Models.ObserverDiscovery", b =>
                {
                    b.HasOne("PlanetHunters.Models.Discovery", "Discovery")
                        .WithMany("Observers")
                        .HasForeignKey("DiscoveryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PlanetHunters.Models.Astronomer", "Observer")
                        .WithMany("ObservationsOfDiscoveries")
                        .HasForeignKey("ObserverId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PlanetHunters.Models.Planet", b =>
                {
                    b.HasOne("PlanetHunters.Models.Discovery", "Discovery")
                        .WithMany("Planets")
                        .HasForeignKey("DiscoveryId");

                    b.HasOne("PlanetHunters.Models.StarSystem", "HostStarSystem")
                        .WithMany("Planets")
                        .HasForeignKey("HostStarSystemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PlanetHunters.Models.Star", b =>
                {
                    b.HasOne("PlanetHunters.Models.Discovery", "Discovery")
                        .WithMany("Stars")
                        .HasForeignKey("DiscoveryId");

                    b.HasOne("PlanetHunters.Models.StarSystem", "HostStarSystem")
                        .WithMany("Stars")
                        .HasForeignKey("HostStarSystemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
